# Generated by Django 6.1 on 2026-08-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('model_year', models.IntegerField(blank=True, null=True)),
                ('factory_year', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('mileage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('model_year', models.IntegerField(blank=True, null=True)),
                ('factory_year', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('mileage', models.FloatField()),
            ],
        ),
    ]
