# Generated by Django 6.1 on 2026-08-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_brands_vehicletype_alter_bike_brand_alter_car_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='vehicle_types',
            field=models.ManyToManyField(related_name='brands', to='cars.vehicletype'),
        ),
    ]
