# Generated by Django 6.1 on 2026-08-31 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_bike_photo_car_photo_alter_brands_vehicle_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='car',
            name='photo',
        ),
        migrations.CreateModel(
            name='BikeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='bikes_img/')),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.bike')),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cars_img/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
        ),
    ]
