# Generated by Django 6.1 on 2026-09-06 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_remove_bike_photo_remove_car_photo_bikeimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikeimage',
            name='bike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.bike'),
        ),
    ]
