# Generated by Django 6.1 on 2026-09-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_bikeimage_bike'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
