# Generated by Django 6.1.1 on 2026-09-22 13:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


def copy_legacy_vehicles(apps, schema_editor):
    """Preserva os carros, motos e imagens criados antes da unificação."""

    Bike = apps.get_model('cars', 'Bike')
    BikeImage = apps.get_model('cars', 'BikeImage')
    Car = apps.get_model('cars', 'Car')
    CarImage = apps.get_model('cars', 'CarImage')
    Vehicle = apps.get_model('cars', 'Vehicle')
    VehicleImage = apps.get_model('cars', 'VehicleImage')
    VehicleType = apps.get_model('cars', 'VehicleType')

    car_type = VehicleType.objects.filter(name__icontains='car').first()
    if car_type is None:
        car_type = VehicleType.objects.create(name='Carro')

    bike_type = VehicleType.objects.filter(name__icontains='moto').first()
    if bike_type is None:
        bike_type = VehicleType.objects.filter(name__icontains='bike').first()
    if bike_type is None:
        bike_type = VehicleType.objects.create(name='Moto')

    def migrate_vehicle(legacy, vehicle_type, image_model, relation_field):
        price = Decimal(str(legacy.price))
        vehicle = Vehicle.objects.create(
            vehicle_type_id=vehicle_type.pk,
            brand_id=legacy.brand_id,
            model=legacy.model,
            model_year=legacy.model_year,
            factory_year=legacy.factory_year,
            purchase_price=price,
            asking_price=price,
            mileage=max(int(legacy.mileage or 0), 0),
            status='available',
            description=legacy.description or '',
        )
        images = image_model.objects.filter(**{f'{relation_field}_id': legacy.pk})
        for index, legacy_image in enumerate(images):
            if legacy_image.photo:
                VehicleImage.objects.create(
                    vehicle_id=vehicle.pk,
                    photo=legacy_image.photo.name,
                    is_cover=index == 0,
                )

    for car in Car.objects.all():
        migrate_vehicle(car, car_type, CarImage, 'car')
    for bike in Bike.objects.all():
        migrate_vehicle(bike, bike_type, BikeImage, 'bike')


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_bike_description_car_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={'ordering': ('name',), 'verbose_name': 'marca', 'verbose_name_plural': 'marcas'},
        ),
        migrations.AlterModelOptions(
            name='vehicletype',
            options={'ordering': ('name',), 'verbose_name': 'tipo de veículo', 'verbose_name_plural': 'tipos de veículo'},
        ),
        migrations.AlterField(
            model_name='brands',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='brands',
            name='vehicle_types',
            field=models.ManyToManyField(blank=True, related_name='brands', to='cars.vehicletype', verbose_name='tipos de veículo'),
        ),
        migrations.AlterField(
            model_name='vehicletype',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='nome'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('phone', models.CharField(max_length=30, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('document', models.CharField(blank=True, help_text='Opcional. Use somente documentos fictícios.', max_length=30, verbose_name='documento')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='cadastrado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('document', ''), _negated=True), fields=('document',), name='unique_non_empty_customer_document')],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200, verbose_name='modelo')),
                ('model_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='ano do modelo')),
                ('factory_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='ano de fabricação')),
                ('color', models.CharField(blank=True, max_length=60, verbose_name='cor')),
                ('license_plate', models.CharField(blank=True, help_text='Opcional. Use somente dados fictícios no projeto.', max_length=10, null=True, unique=True, verbose_name='placa')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='preço de compra')),
                ('asking_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='preço anunciado')),
                ('mileage', models.PositiveIntegerField(default=0, verbose_name='quilometragem')),
                ('status', models.CharField(choices=[('available', 'Disponível'), ('reserved', 'Reservado'), ('sold', 'Vendido')], db_index=True, default='available', max_length=12, verbose_name='status')),
                ('entry_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='entrada no estoque')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='cars.brands', verbose_name='marca')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='cars.vehicletype', verbose_name='tipo')),
            ],
            options={
                'verbose_name': 'veículo',
                'verbose_name_plural': 'veículos',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='data da venda')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor final')),
                ('payment_method', models.CharField(choices=[('cash', 'Dinheiro'), ('pix', 'Pix'), ('financing', 'Financiamento'), ('card', 'Cartão'), ('other', 'Outro')], default='pix', max_length=20, verbose_name='forma de pagamento')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmada'), ('canceled', 'Cancelada')], db_index=True, default='confirmed', max_length=12, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='registrada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='cars.customer', verbose_name='cliente')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='cars.vehicle', verbose_name='veículo')),
            ],
            options={
                'verbose_name': 'venda',
                'verbose_name_plural': 'vendas',
                'ordering': ('-sale_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='vehicles/', verbose_name='foto')),
                ('is_cover', models.BooleanField(default=False, verbose_name='capa')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='enviada em')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.vehicle', verbose_name='veículo')),
            ],
            options={
                'verbose_name': 'imagem do veículo',
                'verbose_name_plural': 'imagens dos veículos',
                'ordering': ('-is_cover', 'id'),
            },
        ),
        migrations.RunPython(copy_legacy_vehicles, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='bikeimage',
            name='bike',
        ),
        migrations.RemoveField(
            model_name='car',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='carimage',
            name='car',
        ),
        migrations.DeleteModel(
            name='Bike',
        ),
        migrations.DeleteModel(
            name='BikeImage',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='CarImage',
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['status', 'entry_date'], name='vehicle_stock_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['brand', 'model'], name='vehicle_search_idx'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'confirmed')), fields=('vehicle',), name='unique_confirmed_sale_per_vehicle'),
        ),
    ]
